config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root "characters#user_characters", as: :authenticated_root
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :characters do
    collection do
      get 'leaderboard'
      get 'thaumaturge'
      get 'arena'
    end
    member do
      get '/combat_result/:id', to: 'combat#combat_result', as: :combat_result
      post 'select', to: 'characters#select'
      get 'talents'
      post 'gain_experience'
      post 'learn_skill'
      post 'unlearn_skill'
      post 'complete_hunt'
      post 'add_to_inventory/:item_id', to: 'characters#add_to_inventory', as: :add_to_inventory
      delete 'remove_from_inventory/:item_id', to: 'characters#remove_from_inventory', as: :remove_from_inventory
      post '/combat', to: 'combat#combat', as: :combat
      post 'equip_item/:item_id', to: 'characters#equip_item', as: :equip_item
      post 'unequip_item/:item_id', to: 'characters#unequip_item', as: :unequip_item
      post 'sell_item/:item_id', to: 'characters#sell_item', as: :sell_item
      post 'use_elixir/:item_id', to: 'characters#use_elixir', as: :use_elixir
      post 'equip_prompt'
      post 'spend_skill_point'
      post 'heal'
      post 'paragon_increase_attack'
      post 'paragon_increase_armor'
      post 'paragon_increase_spellpower'
      post 'paragon_increase_magic_resistance'
      post 'paragon_increase_critical_strike_chance'
      post 'paragon_increase_critical_strike_damage'
      post 'paragon_increase_total_health'
      post 'paragon_increase_global_damage'
      post 'paragon_reset_attack'
      post 'paragon_reset_armor'
      post 'paragon_reset_spellpower'
      post 'paragon_reset_magic_resistance'
      post 'paragon_reset_critical_strike_chance'
      post 'paragon_reset_critical_strike_damage'
      post 'paragon_reset_total_health'
      post 'paragon_reset_global_damage'
      patch 'select_hunt'
    end
  end

  resources :items

  resources :forge, only: [:index] do
    collection do
      post 'upgrade', to: 'forge#upgrade'
    end
  end

  resources :hunts, only: [:index] do
    member do
      post '/combat', to: 'combat#combat', as: :combat
      post 'accept_hunt', to: 'hunts#accept_hunt'
      post 'cancel_hunt', to: 'hunts#cancel_hunt'
    end
  end

  resources :quests, only: [:index] do
    member do
      post 'accept', to: 'quests#accept_quest'
      post 'cancel', to: 'quests#cancel_quest'
    end
  end

  resources :guilds do
    member do
      post 'invite_member'
      post 'respond_to_invitation'
      post 'apply_to_join_guild'
      delete 'disband'
    end
  end

  get '/user_characters', to: 'characters#user_characters', as: 'user_characters'
  post 'reset_merchant_items', to: 'items#reset_merchant_items', as: :reset_merchant_items

end

app/controllers/combat_controller.rb
class CombatController < ApplicationController
    def initialize_combat_variables
        @result = nil
        @combat_logs = []
        @turn_count = 1

        @character_has_missed = false
        @character_has_evaded = false
        @character_has_crit = false
        @character_has_ignored_pain = false
        @character_has_blocked = false

        @opponent_has_missed = false
        @opponent_has_evaded = false
        @opponent_has_crit = false
        @opponent_has_ignored_pain = false
        @opponent_has_blocked = false

        @character.piety = false
        @opponent.piety = false
        @character.nullify = false
        @opponent.nullify = false
        @character.ephemeral_rebirth = false
        @opponent.ephemeral_rebirth = false
        @character.blessing_of_kings = false
        @opponent.blessing_of_kings = false
        @character.deathsbargain = false
        @opponent.deathsbargain = false
        @character.took_damage = false
        @opponent.took_damage = false

        @opponent_health_in_combat = @opponent.total_health.to_i

        @character_attack = (@character.total_min_attack + @character.total_max_attack).to_i
        @character_spellpower = (@character.total_min_spellpower + @character.total_max_spellpower).to_i
        @character_necrosurge = (@character.total_min_necrosurge + @character.total_max_necrosurge).to_i
        @character_critical_strike_chance = (@character.total_critical_strike_chance + @character.buffed_critical_strike_chance).to_d
        @character_critical_strike_damage = (@character.total_critical_strike_damage + @character.buffed_critical_strike_damage).to_d
        @character_armor = (@character.total_armor + @character.buffed_armor).to_i
        @character_magic_resistance = (@character.total_magic_resistance + @character.buffed_magic_resistance).to_i
        @character_critical_resistance = (@character.total_critical_resistance + @character.buffed_critical_resistance).to_i
        @character_damage_reduction = (@character.total_damage_reduction + @character.buffed_damage_reduction).to_d
        @character_fire_resistance = (@character.total_fire_resistance + @character.buffed_fire_resistance).to_i
        @character_cold_resistance = (@character.total_cold_resistance + @character.buffed_cold_resistance).to_i
        @character_lightning_resistance = (@character.total_lightning_resistance + @character.buffed_lightning_resistance).to_i
        @character_poison_resistance = (@character.total_lightning_resistance + @character.buffed_poison_resistance).to_i

        @opponent_attack = (@opponent.total_min_attack + @opponent.total_max_attack).to_i
        @opponent_spellpower = (@opponent.total_min_spellpower + @opponent.total_max_spellpower).to_i
        @opponent_necrosurge = (@opponent.total_min_necrosurge + @opponent.total_max_necrosurge).to_i
        @opponent_critical_strike_chance = (@opponent.total_critical_strike_chance + @opponent.buffed_critical_strike_chance).to_d
        @opponent_critical_strike_damage = (@opponent.total_critical_strike_damage + @opponent.buffed_critical_strike_damage).to_d
        @opponent_armor = (@opponent.total_armor + @opponent.buffed_armor).to_i
        @opponent_magic_resistance = (@opponent.total_magic_resistance + @opponent.buffed_magic_resistance).to_i
        @opponent_critical_resistance = (@opponent.total_critical_resistance + @opponent.buffed_critical_resistance).to_i
        @opponent_damage_reduction = (@opponent.total_damage_reduction + @opponent.buffed_damage_reduction).to_d
        @opponent_fire_resistance = (@opponent.total_fire_resistance + @opponent.buffed_fire_resistance).to_i
        @opponent_cold_resistance = (@opponent.total_cold_resistance + @opponent.buffed_cold_resistance).to_i
        @opponent_lightning_resistance = (@opponent.total_lightning_resistance + @opponent.buffed_lightning_resistance).to_i
        @opponent_poison_resistance = (@opponent.total_lightning_resistance + @opponent.buffed_poison_resistance).to_i

        @character_deep_wounds_turn = 0
        @opponent_deep_wounds_turn = 0
        @character_blessing_of_kings_turn = 0
        @opponent_blessing_of_kings_turn = 0
        @character_river_of_blood_stack = 0
        @opponent_river_of_blood_stack = 0
    end

    def reset_buffed_stats
        @character.set_default_values_for_buffed_stats
        @opponent.set_default_values_for_buffed_stats
    end

    def determine_opponent
        @character = current_user.selected_character
        opponent_id = params[:opponent_id].to_i
        if Character.exists?(opponent_id) && opponent_id.to_i != current_user.selected_character.id
            @opponent = Character.find_by(id:opponent_id)
        end
    end

    def determine_combat_result
        @result =
        if @character.total_health.positive?
            '<strong style="font-size: 18px;">Victory</strong>'
        elsif @opponent_health_in_combat.positive?
            '<strong style="font-size: 18px;">Defeat</strong>'
        end
    end

    def combat_result
        combat_result = CombatResult.find(params[:combat_result_id])
        @opponent = combat_result.opponent
        @character = combat_result.character
        @combat_logs = combat_result.combat_logs
        @result = combat_result.result
        @opponent_health_in_combat = combat_result.opponent_health_in_combat
    end

    def save_combat_result
        combat_result = CombatResult.create(
            character: current_user.selected_character,
            opponent: @opponent,
            combat_logs: @combat_logs,
            result: @result,
            opponent_health_in_combat: @opponent_health_in_combat
        )
        # Redirect to combat result page with combat result data
        redirect_to combat_result_character_path(combat_result_id: combat_result.id)
        @character.update_column(:total_health, @character.total_health)
    end

    def switch_turns
        @character_turn = !@character_turn
        @opponent_turn = !@opponent_turn
    end

    def combat_loop
        log_message =  "<span style='font-size: larger;'><strong>Turn #{@turn_count}</strong></span>"
            if @character_turn
                log_message += ": <span style='font-size: larger;'><strong>#{@character.character_name.upcase}</strong></span>"
            elsif @opponent_turn
                log_message += ": <span style='font-size: larger;'><strong>#{@opponent.character_name.upcase}</strong></span>"
            end
        @combat_logs << log_message
        while @character.total_health.positive? && @opponent_health_in_combat.positive?
            if @character_turn
                character_turn
            elsif @opponent_turn
                opponent_turn
            end
            switch_turns
            if @character.total_health.positive? && @opponent_health_in_combat.positive?
                @turn_count += 1
                log_message =  "<span style='font-size: larger;'><strong>Turn #{@turn_count}</strong></span>"
                if @character_turn
                    log_message += ": <span style='font-size: larger;'><strong>#{@character.character_name.upcase}</strong></span>"
                elsif @opponent_turn
                    log_message += ": <span style='font-size: larger;'><strong>#{@opponent.character_name.upcase}</strong></span>"
                end
                @combat_logs << log_message
            end
            # Check if character or opponent is defeated
            break unless @character.total_health.positive? && @opponent_health_in_combat.positive?
        end
        # Determine combat result
        determine_combat_result
        log_message =  "#{@result}"
        @combat_logs << log_message
        # Default values for buffs at the end of the combat to prevent saving buffs
        reset_buffed_stats
    end

    def combat
        # Retrieve the player's character and determine the opponent
        @character = current_user.selected_character
        @opponent = determine_opponent
        # Check if the user has enough health to engage in combat
        if @character.total_health == 0
            flash[:alert] = "You do not have enough Health to engage in combat."
                respond_to do |format|
                    format.js { render js: "window.location.reload()" }
                end
            return
        end
        # Default values for buffs
        reset_buffed_stats
        # Initialize combat
        initialize_combat_variables
        # Randomly determine the first turn
        @character_turn = rand(2).zero?
        @opponent_turn = !@character_turn
        # Combat has started, show a log
        log_message = '<strong style="font-size: 18px;">Battle has begun</strong>'
        @combat_logs << log_message
        combat_loop
        # Save the combat result
        save_combat_result
    end

    def calculate_damage(damage_type)
        if @character_turn
            case damage_type
                when :physical
                    if (@character.neck.present? && @character.neck.name == "The Nexus")
                        damage_roll = @character_attack
                    else
                        damage_roll = rand((@character.total_min_attack + @character.buffed_min_attack)..(@character.total_max_attack + @character.buffed_max_attack))
                    end
                    if (rand(0..100) <= @character_critical_strike_chance)
                        damage =  ((damage_roll + (damage_roll * @character.total_global_damage)) + (damage_roll * @character_critical_strike_damage))
                        @character_has_crit = true
                    else
                        damage = (damage_roll + (damage_roll * @character.total_global_damage))
                    end
                    if (@character.main_hand.present? && @character.main_hand.name == "Nemesis" && @opponent_health_in_combat >= (@opponent.total_max_health * 0.70))

app/views/combat/combat_result.html.erb
  <div class="text-center mt-5 ">
    <div class="row justify-content-center">
      <!-- Character Card -->
      <div class="col">
        <div class="card text-center" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 20px; height: auto; width: 500px;">
          <div style="position: relative; max-width: 100%;">
            <%= image_tag(@character.race_image, style: 'max-width:100%; height:auto; border: 5px solid #000; box-shadow: 2px 2px 10px #888888;', class: 'card-img-top', alt: "character_image") %>
            <div style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); width: 90%; text-align: center;">
              <h5 style=" color: white; font-size: 22px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000;"> <%= @character.character_name %></h5>
              <% if @character.guild.present? %>
                <h5 style=" color: white; font-size: 22px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000;"> < <%= @character.guild.name %> ></h5>
              <% end %>
            </div>
          </div>
          <div id="character-health-bar" class="progress" style="height: 30px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888; position: relative; margin-top : 20px;">
            <div class="progress-bar bg-success" role="progressbar" style="width: <%= (@character.total_health.to_f / @character.total_max_health) * 100 %>%;"></div>
            <h5 style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"><%= @character.total_health.to_i %> / <%= @character.total_max_health %></h5>
          </div>
        </div>
      </div>
        <div class="col">
            <div class="row justify-content-center">
                <div class="col">
                    <h1 class="text-danger" style="margin-top: 275px;">VS</h1>
                </div>
            </div>
        </div>
      <!-- Opponent Card -->
      <div class="col">
        <div class="card text-center" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 20px; height: auto; width: 500px;">
          <% if @opponent.is_a?(Monster) %>
          <div style="position: relative; max-width: 100%;">
            <%= image_tag(@opponent.monster_image, style: 'max-width:100%; height:auto; border: 5px solid #000; box-shadow: 2px 2px 10px #888888;', class: 'card-img-top', alt: "opponent_image") %>
            <h5 style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); color: white; font-size: 24px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000; width: 90%; text-align: center;"><%= @opponent.monster_name %></h5>
          </div>
          <% elsif @opponent.is_a?(Character) %>
          <div style="position: relative; max-width: 100%;">
            <%= image_tag(@opponent.race_image, style: 'max-width:100%; height:auto; border: 5px solid #000; box-shadow: 2px 2px 10px #888888;', class: 'card-img-top', alt: "opponent_image") %>
            <div style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); width: 90%; text-align: center;">
              <h5 style=" color: white; font-size: 22px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000;"> <%= @opponent.character_name %></h5>
              <% if @opponent.guild.present? %>
                <h5 style=" color: white; font-size: 22px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000;"> < <%= @opponent.guild.name %> ></h5>
              <% end %>
            </div>
          </div>
          <% end %>
            <div id="opponent-health-bar" class="progress" style="height: 30px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888; position: relative; margin-top: 20px;">
              <div class="progress-bar bg-danger" role="progressbar" style="width: <%= (@opponent_health_in_combat.to_f / @opponent.total_max_health) * 100 %>%;"></div>
              <h5 style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"><%= @opponent_health_in_combat.to_i %> / <%= @opponent.total_max_health %></h5>
            </div>
        </div>
      </div>
    </div>

    <% if @result.present? %>
      <!-- Victory or Defeat Prompt -->
      <div class="row justify-content-center mt-5 mb-3">
        <div id="combat-result" class="col-md-6">
          <% if @result == '<strong style="font-size: 18px;">Victory</strong>' && @hunt.present? %>
            <audio autoplay id="victoryAudio"><source src="/assets/victory.mp3" type="audio/mpeg"></audio>
            <h3>- <span class="text-success">Victory</span> -</h3>
            <%= form_tag(complete_hunt_character_path(@character), method: :post) do %>
              <%= hidden_field_tag :experience_reward, @hunt.experience_reward %>
              <%= hidden_field_tag :hunt_id, @hunt.id %>
              <%= submit_tag 'Complete', class: 'btn btn-outline-success mt-2' %>
            <% end %>
          <% elsif @result == '<strong style="font-size: 18px;">Victory</strong>'%>
            <audio autoplay id="victoryAudio"><source src="/assets/victory.mp3" type="audio/mpeg"></audio>
            <h3>- <span class="text-success">Victory</span> -</h3>
          <% elsif @result == '<strong style="font-size: 18px;">Defeat</strong>' %>
            <audio autoplay id="defeatAudio"><source src="/assets/defeat.mp3" type="audio/mpeg"></audio>
            <h3>- <span class="text-danger">Defeat</span> -<br style="mb-5"><a href="<%= character_path(@character) %>" style="font-size:18px;">Retreat</a></h3>
          <% end %>
        </div>
      </div>
    <% end %>

    <!-- Combat Log -->
    <div class="card text-center" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding-top: 15px; height: auto; width: auto;">
        <h4 class="card-header text-white bg-primary" style="width: 200px; margin: 0 auto;">Combat details</h4>
        <hr style="margin-bottom: 0;">
        <div class="row justify-content-center" style="width: auto; height: 400px; overflow: auto;">
            <div>
                <div class="card-body">
                    <div id="combat-log-container" class="combat-log">
                        <% @combat_logs.each_with_index do |log, index| %>
                            <p><%= log&.html_safe %></p>
                            <% unless index == @combat_logs.size - 1 %>
                                <hr class="mx-auto" style="width: 20%">
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>