config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root "characters#user_characters", as: :authenticated_root
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :characters do
    collection do
      get 'leaderboard'
      get 'thaumaturge'
      get 'arena'
    end
    member do
      get '/combat_result/:id', to: 'combat#combat_result', as: :combat_result
      post 'select', to: 'characters#select'
      get 'talents'
      post 'gain_experience'
      post 'learn_skill'
      post 'unlearn_skill'
      post 'complete_hunt'
      post 'add_to_inventory/:item_id', to: 'characters#add_to_inventory', as: :add_to_inventory
      delete 'remove_from_inventory/:item_id', to: 'characters#remove_from_inventory', as: :remove_from_inventory
      post '/combat', to: 'combat#combat', as: :combat
      post 'equip_item/:item_id', to: 'characters#equip_item', as: :equip_item
      post 'unequip_item/:item_id', to: 'characters#unequip_item', as: :unequip_item
      post 'sell_item/:item_id', to: 'characters#sell_item', as: :sell_item
      post 'use_elixir/:item_id', to: 'characters#use_elixir', as: :use_elixir
      post 'equip_prompt'
      post 'spend_skill_point'
      post 'heal'
      post 'paragon_increase_attack'
      post 'paragon_increase_armor'
      post 'paragon_increase_spellpower'
      post 'paragon_increase_magic_resistance'
      post 'paragon_increase_critical_strike_chance'
      post 'paragon_increase_critical_strike_damage'
      post 'paragon_increase_total_health'
      post 'paragon_increase_global_damage'
      post 'paragon_reset_attack'
      post 'paragon_reset_armor'
      post 'paragon_reset_spellpower'
      post 'paragon_reset_magic_resistance'
      post 'paragon_reset_critical_strike_chance'
      post 'paragon_reset_critical_strike_damage'
      post 'paragon_reset_total_health'
      post 'paragon_reset_global_damage'
      patch 'select_hunt'
    end
  end

  resources :items

  resources :forge, only: [:index] do
    collection do
      post 'upgrade', to: 'forge#upgrade'
    end
  end

  resources :hunts, only: [:index] do
    member do
      post '/combat', to: 'combat#combat', as: :combat
      post 'accept_hunt', to: 'hunts#accept_hunt'
      post 'cancel_hunt', to: 'hunts#cancel_hunt'
    end
  end

  resources :quests, only: [:index] do
    member do
      post 'accept', to: 'quests#accept_quest'
      post 'cancel', to: 'quests#cancel_quest'
    end
  end

  resources :guilds do
    member do
      post 'invite_member'
      post 'respond_to_invitation'
      post 'apply_to_join_guild'
      delete 'disband'
    end
  end

  get '/user_characters', to: 'characters#user_characters', as: 'user_characters'
  post 'reset_merchant_items', to: 'items#reset_merchant_items', as: :reset_merchant_items

end

app/models/guild.rb
class Guild < ApplicationRecord
  MAX_MEMBERS = 30

  belongs_to :leader, class_name: 'Character'
  has_many :members, class_name: 'Character'

  validates :name, presence: true, uniqueness: true
  validate :validate_max_members

  enum membership_status: { open: 0, invite_only: 1 }

  def validate_max_members
    if members.size >= MAX_MEMBERS
      errors.add(:base, "You cannot have more guild members")
    end
  end
end

app/controllers/guilds_controller.rb
class GuildsController < ApplicationController

  def new
    @guild = Guild.new
    @guilds = Guild.all
  end

  def show
    @guild = Guild.find(params[:id])
    @members = @guild.members
  end

  def create
    @guild = Guild.new(guild_params)
    @guild.leader = current_user.selected_character

    if @guild.save
      # Assign the guild to the character
      current_user.selected_character.update(guild: @guild)
      redirect_to @guild, notice: 'Guild was successfully created.'
    else
      render :new
    end
  end

  def disband
    @guild = Guild.find(params[:id])
    if @guild.leader == current_user.selected_character
      @guild.members.update_all(guild_id: nil)
      @guild.destroy
      respond_to do |format|
        format.js { render js: "window.location.reload(); alert('Guild disbanded successfully.');" }
      end
    else
      redirect_to @guild, notice: "Only the guild leader can disband the guild."
    end
  end

  def invite_member
    invited_character = Character.find(params[:character_id])
    if @guild.members.size < Guild::MAX_MEMBERS && @guild.invite_only?
      Invitation.create(guild: @guild, invited_character: invited_character, inviting_character: current_user.character)
      redirect_to @guild, notice: 'Invitation sent successfully.'
    else
      redirect_to @guild, alert: 'Unable to send invitation.'
    end
  end

  def respond_to_invitation
    invitation = @guild.invitations.find(params[:invitation_id])
    if params[:response] == 'accept'
      invitation.accepted!
      invitation.invited_character.update(guild: @guild)
      redirect_to @guild, notice: 'Invitation accepted.'
    elsif params[:response] == 'reject'
      invitation.rejected!
      redirect_to @guild, notice: 'Invitation rejected.'
    else
      redirect_to @guild, alert: 'Invalid response.'
    end
  end

  def apply_to_join_guild
    @guild = Guild.find(params[:guild_id])
    if current_user.selected_character.guild.nil?
      current_user.selected_character.update(guild: @guild)
      redirect_to @guild, notice: "#{@guild.name} Joined."
    else
      redirect_to @guild, alert: "You are already a member of a guild."
    end
  end

  private

  def guild_params
    params.require(:guild).permit(:name, :membership_status)
  end

end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/views/guilds/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <!-- Form to create a new guild -->
      <div class="card text-left mx-auto" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 20px; position: relative; height: 500px; width: 600px;">
        <h4 class="card-header text-center text-white bg-primary mb-5" style="width: 200px; margin: 0 auto;">Create a Guild</h4>
        <%= form_with(model: @guild, local: true) do |form| %>
          <% if @guild.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@guild.errors.count, 'error') %> prohibited this guild from being saved:</h2>
              <ul>
                <% @guild.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.text_field :name, class: 'form-control', placeholder: 'Guild name', style: 'text-align: center; font-size: 20px;' %>
          </div>
          <div class="field mt-3" style="text-align: center;">
            <label><strong>Membership Status</strong></label>
            <div>
              <%= form.select :membership_status, Guild.membership_statuses.keys.map { |status| [status.humanize, status] }, {}, { class: 'form-control' } %>
            </div>
          </div>
          <div class="actions" style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); margin-bottom: 10px;">
            <%= form.submit 'Create', class: "btn btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- List of existing guilds -->
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card text-center" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding-top: 15px;">
        <h4 class="card-header text-white bg-primary" style="width: 200px; margin: 0 auto;">Join a Guild</h4>
        <hr style="margin-bottom: 0;">
        <div class="row justify-content-center" style="max-height: 400px; overflow-y: auto;">
          <div class="card-body">
            <% @guilds.each do |guild| %>
              <div class="row">
                <div class="col">
                  <h5><%= link_to guild.name, guild %></h5>
                  <p>Members: <%= guild.members.count %> / 30</p>
                </div>
              </div>
              <% unless guild == @guilds.last %>
                <hr>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/guilds/show.html.erb
<div class="card text-left mt-5 mx-auto" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 20px; width: 500px; margin-right: 20px; position: relative;">
  <h2 class="text-center"><strong><%= @guild.name %></strong></h2>
  <p><strong>Leader:</strong> <%= @guild.leader.character_name %></p>
  <p><strong>Membership Status:</strong> <%= @guild.membership_status.humanize %></p>
  
  <% if @guild.membership_status == 'invite_only' && @guild.leader == current_user.selected_character %>
    <div class="actions" style="text-align: center;">
      <%= link_to "Invite Member", invite_member_guild_path(@guild), class: "btn btn-primary" %>
    </div>
  <% end %>

  <% if current_user.selected_character == @guild.leader %>
    <div class="actions" style="text-align: center;">
      <%= form_with(model: @guild, url: disband_guild_path(@guild), method: :delete, local: true) do |form| %>
        <%= form.submit "Disband", class: "btn btn-danger" %>
      <% end %>
    </div>
  <% end %>

  <% if current_user.selected_character.guild.nil? %>
    <div class="actions" style="text-align: center;">
      <%= form_tag(apply_to_join_guild_guild_path(guild_id: @guild.id), method: :post, class: "join-guild-form") do %>
        <%= submit_tag "Apply to Join", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>

  <hr>

  <h3 class="text-center">Members</h3>
  <ul class="list-group">
    <% @guild.members.each do |member| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span><%= member.character_name %> (Level <%= member.level %> <%= member.character_class.capitalize %>)</span>
        <span><%= link_to 'View Profile', character_path(member), class: 'btn btn-outline-primary btn-sm' %></span>
      </li>
    <% end %>
  </ul>
</div>