config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root "characters#user_characters", as: :authenticated_root
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :characters do
    collection do
      get 'leaderboard'
      get 'thaumaturge'
      get 'arena'
    end
    member do
      get '/combat_result/:id', to: 'combat#combat_result', as: :combat_result
      post 'select', to: 'characters#select'
      get 'talents'
      post 'gain_experience'
      post 'learn_skill'
      post 'unlearn_skill'
      post 'complete_hunt'
      post 'add_to_inventory/:item_id', to: 'characters#add_to_inventory', as: :add_to_inventory
      delete 'remove_from_inventory/:item_id', to: 'characters#remove_from_inventory', as: :remove_from_inventory
      post '/combat', to: 'combat#combat', as: :combat
      post 'equip_item/:item_id', to: 'characters#equip_item', as: :equip_item
      post 'unequip_item/:item_id', to: 'characters#unequip_item', as: :unequip_item
      post 'sell_item/:item_id', to: 'characters#sell_item', as: :sell_item
      post 'use_elixir/:item_id', to: 'characters#use_elixir', as: :use_elixir
      post 'equip_prompt'
      post 'spend_skill_point'
      post 'heal'
      post 'paragon_increase_attack'
      post 'paragon_increase_armor'
      post 'paragon_increase_spellpower'
      post 'paragon_increase_magic_resistance'
      post 'paragon_increase_critical_strike_chance'
      post 'paragon_increase_critical_strike_damage'
      post 'paragon_increase_total_health'
      post 'paragon_increase_global_damage'
      post 'paragon_reset_attack'
      post 'paragon_reset_armor'
      post 'paragon_reset_spellpower'
      post 'paragon_reset_magic_resistance'
      post 'paragon_reset_critical_strike_chance'
      post 'paragon_reset_critical_strike_damage'
      post 'paragon_reset_total_health'
      post 'paragon_reset_global_damage'
      patch 'select_hunt'
    end
  end

  resources :items

  resources :forge, only: [:index] do
    collection do
      post 'upgrade', to: 'forge#upgrade'
    end
  end

  resources :hunts, only: [:index] do
    member do
      post '/combat', to: 'combat#combat', as: :combat
      post 'accept_hunt', to: 'hunts#accept_hunt'
      post 'cancel_hunt', to: 'hunts#cancel_hunt'
    end
  end

  resources :quests, only: [:index] do
    member do
      post 'accept', to: 'quests#accept_quest'
      post 'cancel', to: 'quests#cancel_quest'
    end
  end

  resources :guilds do
    member do
      post 'invite_member'
      post 'respond_to_invitation'
      post 'apply_to_join_guild'
      delete 'disband'
    end
  end

  get '/user_characters', to: 'characters#user_characters', as: 'user_characters'
  post 'reset_merchant_items', to: 'items#reset_merchant_items', as: :reset_merchant_items

end

app/models/hunt.rb
class Hunt < ApplicationRecord
    belongs_to :character, optional: true
    has_many :monsters
    belongs_to :combat_result, optional: true



    def scaled_experience_reward(character_level)
        scaling_factor = case character_level
            when 1..9 then 1.0
            when 10..19 then 0.90
            when 20..39 then 0.80
            when 40..49 then 0.70
            when 50..59 then 0.60
            when 60..69 then 0.50
            when 70..79 then 0.40
            when 80..99 then 0.30
            when 100..199 then 0.20
            when 200..299 then 0.10
            when 300..Float::INFINITY then 0.05
            else 1.0
            end

        base_experience = (self.experience_reward * scaling_factor).round
        level_difference = character_level - self.level_requirement

        if level_difference <= 5
            # Character level <= Hunt level + 5: XP = (100 %)
            base_experience
        elsif level_difference.between?(6, 9)
            # Character level = Hunt level + 6 to Hunt level + 9
            scaling_percentage = (100 - (level_difference - 5) * 20) / 100.0
            (base_experience * scaling_percentage / 5).round * 5
        else
        # Character level >= Hunt level + 10: XP = (10 %)
            (base_experience * 0.1 / 5).round * 5
        end
    end

end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController
before_action :authenticate_user!

    def index
        @selected_character = Character.find(session[:selected_character_id])
        @accepted_hunt = @selected_character.accepted_hunt
        @available_hunts = Hunt.where.not(id: @accepted_hunt&.id).where('level_requirement <= ?', @selected_character.level)
    end

    def accept_hunt
        @selected_character = Character.find(session[:selected_character_id])

        if @selected_character.accepted_hunt.present?
            redirect_to hunts_path, alert: 'You have already accepted a hunt.'
        else
            @hunt = Hunt.find(params[:id])

            if @selected_character.level < @hunt.level_requirement
                redirect_to hunts_path, alert: 'Your level is too low for this hunt.'
            else
                # Check if character has enough energy for the hunt
                if @selected_character.energy >= @hunt.energy_cost
                    # Deduct energy_cost from character's energy
                    @selected_character.energy -= @hunt.energy_cost
                    @selected_character.save
                    # Update the character_id for the accepted hunt
                    @hunt.update(character_id: @selected_character.id)

                    redirect_to hunts_path, notice: 'Your hunt begins.'
                else
                    redirect_to hunts_path, alert: 'Not enough energy.'
                end
            end
        end
    end

    def cancel_hunt
        @selected_character = Character.find(session[:selected_character_id])
        @selected_character.update(accepted_hunt: nil)
        redirect_to hunts_path, notice: 'Hunt canceled.'
    end

end

app/views/hunts/index.html.erb
<div class="mt-5" style="display: flex; flex-direction: row;">
  <!-- Left Column - Image and Text -->
  <div class="card text-left " style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 20px; height: 600px; width: 500px; margin-right: 20px;">
    <div class="card-body">
        <div style="position: relative; max-width: 100%;">
          <%= image_tag('npcs/milena.jpg', style: 'max-width:100%; height:auto; border: 5px solid #000; box-shadow: 2px 2px 10px #888888;', class: 'card-img-top', alt: "character_image") %>
          <h5 style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); color: white; font-size: 24px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000; width: 90%; text-align: center;">Milena</h5>
        </div>
      <br>

      <% if @accepted_hunt.present? %>
        <p class="card-text">Come back to me when your task is done.</p>
        <p class="card-text">Blessings on your hunt.</p>
        
      <% else %>
        <p class="card-text">I have a couple of problems that need to be taken care of.</p>
        <p class="card-text"> Do you mind taking a look?</p>
      <% end %>
    </div>
  </div>

  <!-- Right Column - Accepted and Available Hunts -->
  <div style="flex-grow: 1; overflow: auto; height: 1218px;">

    <% if @accepted_hunt %>
      <div class="card text-left" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 15px; margin-bottom: 20px; width: 500px; height: 700px; ">
        <h4 class="card-header text-white text-center bg-primary" style="width: auto; margin: 0 auto;">Hunt in progress</h4>
        <div class="card-body">
          <h5 class="card-title"><%= @accepted_hunt.name %></h5>
          <p class="card-text text-center mt-1">Level required : <%= @accepted_hunt.level_requirement %></p>
          <p class="card-text"><%= @accepted_hunt.description %></p>
        </div>
        <br>
        <p class="card-text">Experience : <span class="badge rounded-pill bg-success" style="color: black;"><%= @accepted_hunt.scaled_experience_reward(@selected_character.level) %></span></p>
        <p class="card-text">Gold : <span class="badge rounded-pill bg-warning" style="color: black;"><%= @accepted_hunt.gold_reward %></span></p>
        <% if @accepted_hunt.combat_result %>
          <%= link_to 'Resume', combat_result_path(combat_result_id: @accepted_hunt.combat_result.id)%> 
        <% else %>
          <%= form_tag combat_hunt_path(@accepted_hunt, character_id: @selected_character.id, opponent_id: @accepted_hunt.monster_id), method: :post, remote: true do %>
            <%= submit_tag 'Start Hunting', class: "btn btn-outline-primary" %>
          <% end %>
        <% end %>
        <%= form_tag cancel_hunt_hunt_path(@accepted_hunt), method: :post do %>
          <%= submit_tag 'Cancel', class: "btn btn-outline-danger" %>
        <% end %>
      </div>
    <% else %>
      <% @available_hunts.each do |hunt| %>
        <div class="card text-left" style="border: 2px solid #000; border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 15px; margin-bottom: 10px; width: 500px; height: 400px; ">
          <h4 class="card-header text-center text-white bg-primary" style="width: auto; margin: 0 auto;"><%= hunt.name %></h4>
          <p class="card-text text-center mt-1">Level required : <%= hunt.level_requirement %></p>
          <div class="card-body" style= "overflow-y: show;">
            <p class="card-text" style= "overflow-y: scroll; height: 100px"><%= hunt.description %></p>
          </div>
          <br>
          <p class="card-text">Experience : <span class="badge rounded-pill bg-success" style="color: black;"><%= hunt.scaled_experience_reward(@selected_character.level) %></span></p>
          <p class="card-text">Gold : <span class="badge rounded-pill bg-warning" style="color: black;"><%= hunt.gold_reward %></span></p>
          <%= form_tag accept_hunt_hunt_path(hunt), method: :post do %>
            <%= submit_tag 'Accept', class: "btn btn-outline-primary "%>
          <% end %>
        </div>
      <% end %>
    <% end %>

  </div>
</div>