config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root "characters#user_characters", as: :authenticated_root
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :characters do
    collection do
      get 'leaderboard'
      get 'thaumaturge'
      get 'arena'
    end
    member do
      get '/combat_result/:id', to: 'combat#combat_result', as: :combat_result
      post 'select', to: 'characters#select'
      get 'talents'
      post 'gain_experience'
      post 'learn_skill'
      post 'unlearn_skill'
      post 'complete_hunt'
      post 'add_to_inventory/:item_id', to: 'characters#add_to_inventory', as: :add_to_inventory
      delete 'remove_from_inventory/:item_id', to: 'characters#remove_from_inventory', as: :remove_from_inventory
      post '/combat', to: 'combat#combat', as: :combat
      post 'equip_item/:item_id', to: 'characters#equip_item', as: :equip_item
      post 'unequip_item/:item_id', to: 'characters#unequip_item', as: :unequip_item
      post 'sell_item/:item_id', to: 'characters#sell_item', as: :sell_item
      post 'use_elixir/:item_id', to: 'characters#use_elixir', as: :use_elixir
      post 'equip_prompt'
      post 'spend_skill_point'
      post 'heal'
      post 'paragon_increase_attack'
      post 'paragon_increase_armor'
      post 'paragon_increase_spellpower'
      post 'paragon_increase_magic_resistance'
      post 'paragon_increase_critical_strike_chance'
      post 'paragon_increase_critical_strike_damage'
      post 'paragon_increase_total_health'
      post 'paragon_increase_global_damage'
      post 'paragon_reset_attack'
      post 'paragon_reset_armor'
      post 'paragon_reset_spellpower'
      post 'paragon_reset_magic_resistance'
      post 'paragon_reset_critical_strike_chance'
      post 'paragon_reset_critical_strike_damage'
      post 'paragon_reset_total_health'
      post 'paragon_reset_global_damage'
      patch 'select_hunt'
    end
  end

  resources :items

  resources :forge, only: [:index] do
    collection do
      post 'upgrade', to: 'forge#upgrade'
    end
  end

  resources :hunts, only: [:index] do
    member do
      post '/combat', to: 'combat#combat', as: :combat
      post 'accept_hunt', to: 'hunts#accept_hunt'
      post 'cancel_hunt', to: 'hunts#cancel_hunt'
    end
  end

  resources :quests, only: [:index] do
    member do
      post 'accept', to: 'quests#accept_quest'
      post 'cancel', to: 'quests#cancel_quest'
    end
  end

  resources :guilds do
    member do
      post 'invite_member'
      post 'respond_to_invitation'
      post 'apply_to_join_guild'
      delete 'disband'
    end
  end

  get '/user_characters', to: 'characters#user_characters', as: 'user_characters'
  post 'reset_merchant_items', to: 'items#reset_merchant_items', as: :reset_merchant_items

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :user_characters]

    def new
        @character = current_user.characters.build
    end

    def leaderboard
        @characters = Character.order(level: :desc)
    end

    def thaumaturge
        @character = current_user.selected_character
        @healing_potions = Item.where(item_type: "Healing Potion")
        @elixirs = Item.where(item_type: "Elixir")
    end

    def heal
        @character = current_user.selected_character
        healing_cost = 10

        if @character.total_health < @character.total_max_health
            if @character.gold >= healing_cost
                @character.total_health = @character.total_max_health
                @character.gold -= healing_cost
                @character.save
                flash[:notice] = "You feel refreshed."
            else
                flash[:alert] = "You do not have enough gold."
            end
        else
            flash[:alert] = "Your health is already full."
        end

        respond_to do |format|
        format.js { render js: "window.location.reload()" }
        end
    end

    def create
        @character = current_user.characters.build(character_params)

        @character.set_race_image

        @character.set_default_values_for_buffed_stats

        @character.modify_stats_based_on_race
        @character.modify_attributes_based_on_class
        @character.set_default_values_for_total_stats
        @character.modify_stats_based_on_attributes

        if @character.save
            @character.create_inventory
            @character.assign_skills_based_on_class

        flash[:notice] = 'Character created.'
        redirect_to user_characters_path

        if current_user.characters.count == 1
            flash[:tutorial] = true
        end

        else

            character_name_errors = @character.errors[:character_name]
            if character_name_errors.present?
                flash[:alert] = "Character name #{character_name_errors.join(' and ')}"
            else
                flash[:alert] = 'An error occured. Please try again.'
            end
            redirect_to new_character_path
        end
    end

    def select
        @selected_character = Character.find(params[:id])

        if current_user.selected_character.present?
            current_user.selected_character.update(user: nil)
        end

        session[:selected_character_id] = @selected_character.id
        current_user.update(selected_character: @selected_character)

        redirect_to character_path(@selected_character)
    end

    def user_characters
        @characters = current_user.characters
        if current_user.selected_character.present?
            current_user.selected_character.update(user: nil)
            session[:selected_character_id] = nil
            current_user.update(selected_character: nil)
        end
    end

    def arena
        user_characters = current_user.characters
        user_character = current_user.selected_character
        min_rank = [user_character.arena_rank - 10, 0].max
        max_rank = user_character.arena_rank + 10
        @opponents = Character.where('"arena_rank" >= ? AND "arena_rank" <= ?', min_rank, max_rank)
                                .where.not(id: user_characters.pluck(:id))
                                .where('total_health = total_max_health')
                                .limit(3)
        @combat_results = CombatResult.where(opponent_type: 'Character', opponent_id: current_user.selected_character.id).order(created_at: :desc).limit(10)
    end

    def destroy
        @character = Character.find(params[:id])
        @character.update(accepted_hunt: nil)
        User.where(selected_character_id: @character.id).update_all(selected_character_id: nil)

        @character.destroy

        redirect_to user_characters_path
        flash[:notice]= 'Character was deleted.'
    end

    def show
        @character = Character.find(params[:id])
        @selected_character = current_user.selected_character if current_user.selected_character.present?
        @items = Item.all
        @hunts = Hunt.all
        @skills = @character.skills
    end

    def talents
        @character = current_user.selected_character
        @skills = @character.skills
    end

    def paragon_increase_attack
        @character = current_user.selected_character
        if @character.level >= 100
            if @character.paragon_increase_attack_count < 50
                if @character.paragon_points > 0
                    @character.paragon_attack += 0.01
                    @character.modify_stats_based_on_attributes
                    @character.apply_passive_skills
                    @character.update_elixir_effect
                    @character.decrement(:paragon_points)
                    @character.increment(:paragon_increase_attack_count)
                    @character.save
                else
                    flash[:alert] = "Not enough paragon points."
                end
            else
                flash[:alert] = "You increased this Paragon power to its maximum."
            end
        else
            flash[:alert] = "You must be at least level 100 to unlock Paragon powers."
        end
        respond_to do |format|
        format.js { render js: "window.location.reload()" }
        end
    end

    def paragon_increase_armor
        @character = current_user.selected_character
        if @character.level >= 100
            if @character.paragon_increase_armor_count < 50
                if @character.paragon_points > 0
                    @character.paragon_armor += 0.005
                    @character.modify_stats_based_on_attributes
                    @character.apply_passive_skills
                    @character.update_elixir_effect
                    @character.decrement(:paragon_points)
                    @character.increment(:paragon_increase_armor_count)
                    @character.save
                else
                    flash[:alert] = "Not enough paragon points."
                end
            else
                flash[:alert] = "You increased this Paragon power to its maximum."
            end
        else
            flash[:alert] = "You must be at least level 100 to unlock Paragon powers."
        end
        respond_to do |format|
        format.js { render js: "window.location.reload()" }
        end
    end

    def paragon_increase_spellpower
        @character = current_user.selected_character
        if @character.level >= 100
            if @character.paragon_increase_spellpower_count < 50
                if @character.paragon_points > 0
                    @character.paragon_spellpower += 0.01
                    @character.modify_stats_based_on_attributes
                    @character.apply_passive_skills
                    @character.update_elixir_effect
                    @character.decrement(:paragon_points)
                    @character.increment(:paragon_increase_spellpower_count)
                    @character.save
                else
                    flash[:alert] = "Not enough paragon points."
                end
            else
                flash[:alert] = "You increased this Paragon power to its maximum."
            end
        else
            flash[:alert] = "You must be at least level 100 to unlock Paragon powers."
        end
        respond_to do |format|
        format.js { render js: "window.location.reload()" }
        end
    end

    def paragon_increase_magic_resistance
        @character = current_user.selected_character
        if @character.level >= 100
            if @character.paragon_increase_magic_resistance_count < 50
                if @character.paragon_points > 0
                    @character.paragon_magic_resistance += 0.005
                    @character.modify_stats_based_on_attributes
                    @character.apply_passive_skills
                    @character.update_elixir_effect
                    @character.decrement(:paragon_points)
                    @character.increment(:paragon_increase_magic_resistance_count)
                    @character.save
                else
                    flash[:alert] = "Not enough paragon points."
                end
            else
                flash[:alert] = "You increased this Paragon power to its maximum."
            end
        else
            flash[:alert] = "You must be at least level 100 to unlock Paragon powers."
        end
        respond_to do |format|
        format.js { render js: "window.location.reload()" }
        end
    end

    def paragon_increase_critical_strike_chance
        @character = current_user.selected_character
        if @character.level >= 100
            if @character.paragon_increase_critical_strike_chance_count < 50
                if @character.paragon_points > 0
                    @character.paragon_critical_strike_chance += 0.10
                    @character.modify_stats_based_on_attributes
                    @character.apply_passive_skills
                    @character.update_elixir_effect
                    @character.decrement(:paragon_points)
                    @character.increment(:paragon_increase_critical_strike_chance_count)
                    @character.save
                else
                    flash[:alert] = "Not enough paragon points."
                end
            else
                flash[:alert] = "You increased this Paragon power to its maximum."
            end
        else
            flash[:alert] = "You must be at least level 100 to unlock Paragon powers."
        end
        respond_to do |format|
            format.js { render js: "window.location.reload()" }
        end
    end

    def paragon_increase_critical_strike_damage
        @character = current_user.selected_character
        if @character.level >= 100

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_inventory.html.erb
<div class="card text-left" style="width: 800px; height: auto; border: 2px solid #000; box-shadow: 5px 5px 10px #888888;">
  <div class="card-body">
    <h4 class="card-header text-center text-white bg-primary" style="width: 200px; margin: 0 auto; margin-bottom: 20px;">Inventory</h4>
    <div class="inventory-grid text-center" style="display: grid; grid-template-columns: repeat(5, 1fr);">
      <% (1..10).each do |index| %>
        <div class="row justify-content-center">
          <% item = @selected_character.inventory.items[index - 1] %>
          <% if item %>
            <div class="hover-item" onmousemove="updateTooltipPosition(event, <%= item.id %>)" onmouseover="showTooltip(<%= item.id %>)" onmouseout="hideTooltip(<%= item.id %>)">
              <!-- Tooltip content -->
              <%= display_item_tooltip(item, @character) %>
              <!-- Item Image -->
              <%= image_tag(item.item_image, style: 'width: 100px; height: 100px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888;') %>
              <% if current_page?(items_path) || (controller_name == 'characters' && action_name == 'thaumaturge') %>
                <%= form_with(model: @selected_character, url: sell_item_character_path(@selected_character, item), method: :post, local: true, params: { item_id: item.id }) do |form| %>
                  <%= form.button "Sell", class: "btn btn-outline-danger btn-sm mt-1 mb-1", style:"width: 100px;", id:"sellButton#{item.id}" %>
                  <script>
                    // JavaScript code to show gold price on hover
                    document.getElementById('sellButton<%= item.id %>').addEventListener('mouseover', function() {
                      this.innerText = '+ <%= number_with_delimiter((item.gold_price * 0.65).round) %>';
                    });
                  
                    document.getElementById('sellButton<%= item.id %>').addEventListener('mouseout', function() {
                      this.innerText = 'Sell';
                    });
                  </script>
                <% end %>
              <% elsif ["Healing Potion", "Elixir"].include?(item.item_type) %>
                <%= form_with(model: @selected_character, url: use_elixir_character_path(@selected_character, item), method: :post, local: true, params: { item_id: item.id }) do |form| %>
                  <%= form.button "Use", class: "btn btn-outline-primary btn-sm mt-1 mb-1", style:"width: 100px;" %>
                <% end %>
              <% else %>
                <% unless controller_name == 'forge' && action_name == 'index' %>
                  <%= form_with(model: @selected_character, url: equip_item_character_path(@selected_character, item), method: :post, local: true, params: { item_id: item.id }) do |form| %>
                    <%= form.button "Equip", class: "btn btn-outline-primary btn-sm mt-1 mb-1", style:"width: 100px;" %>
                  <% end %>
                <% end %>
              <% end %>
              <!-- Send to Forge Button -->
              <% if controller_name == 'forge' && action_name == 'index' %>
                <button class="btn btn-outline-primary btn-sm mt-1 mb-1" style="width: 100px;" onclick="sendToForge(<%= item.id %>, '<%= item.upgrade %>', '<%= url_for(item.item_image) %>')">Forge</button>
              <% end %>
            </div>
          <% else %>
            <!-- Empty card content -->
            <div>
              <span class="mb-5" style="display: inline-block; width: 100px; height: 100px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888; background-color: lightgrey;"></span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/arena.html.erb
<audio id="arenaMusic" autoplay loop><source src="/assets/audios/arena.mp3" type="audio/mpeg"></audio>  

<div class="mt-5 mx-auto">
  <div class="row justify-content-center" id="arena-display">
    <% @opponents.each do |opponent| %>
      <div class="col" style="width: 400px;">
        <div class="card text-center" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888;">
          <div class="col text-center">
            <div style="position: relative; max-width: 100%;">
              <%= image_tag(opponent.race_image, style: 'max-width:100%; height:auto; border: 5px solid #000; box-shadow: 2px 2px 10px #888888;', class: 'card-img-top', alt: "character_image") %>
              <h5 style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); color: white; font-size: 24px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000; width: 90%; text-align: center;"><%= opponent.character_name %></h5>
            </div>
          </div>
        </div>
            <% current_experience = opponent.experience %>
            <% required_experience = opponent.required_experience_for_next_level %>
            <% progress_percentage = (current_experience.to_f / required_experience) * 100 %>
            <% if opponent.level < 100 %>
              <div class="progress" style="height: 20px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888; position: relative;" data-tooltip="tooltip" data-placement="bottom" title="<%= current_experience %> / <%= required_experience %> EXP (<%= progress_percentage.to_i %>%)">
                <div class="progress-bar bg-success" role="progressbar" style="width: <%= progress_percentage %>%;"></div>
                <h6 style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"><%=opponent.race.capitalize%> <%=opponent.character_class.capitalize%> Level <%=opponent.level%></h6>
              </div>
            <% else %>
              <div class="progress" style="height: 20px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888; position: relative;" data-tooltip="tooltip" data-placement="bottom" title="<%= current_experience %> / <%= required_experience %> EXP (<%= progress_percentage.to_i %>%)">
                <div class="progress-bar bg-info" role="progressbar" style="width: <%= progress_percentage %>%;"></div>
                <h6 style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);"><%=opponent.race.capitalize%> <%=opponent.character_class.capitalize%> Level <%=opponent.level%></h6>
              </div>
            <% end %>

            <div class="row mt-2 text-center">
              <div class="col">
                <p>Honor :<span style="font-weight: bold"> <%= opponent.arena_rank %></span></p>
              </div>
            </div>

            <div class="row mt-3 text-center">
              <div class="col">
                <%= form_tag combat_character_path(opponent), method: :post do %>
                    <%= hidden_field_tag :opponent_id, opponent.id %>
                    <%= hidden_field_tag :character_id, current_user.selected_character.id %>
                    <%= submit_tag 'Attack', class: "btn btn-outline-danger" %>
                <% end %>
              </div>
            </div>
      </div>
    <% end %>
  </div>
  <br>

<div class="row mt-5">
  <div class="col-md-12 mb-4">
    <div class="card text-center" style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding-top: 15px; height: auto; width: auto;">
      <h4 class="card-header text-white bg-primary" style="width: 200px; margin: 0 auto;">Defence history</h4>
      <hr style="margin-bottom: 0;">
      <div class="row justify-content-center" style="width: auto; max-height: 400px; overflow-y: auto;">
        <div>
          <div class="card-body">
            <% @combat_results.each do |combat_result| %>
              <div class="row">
                <div class="col">
                  <p>
                    <%= link_to "#{combat_result.character.character_name}", character_path(combat_result.character) %>, a Level <%= combat_result.character.level %> <%= combat_result.character.character_class.capitalize %>, has attacked you
                    <% if combat_result.result == '<strong style="font-size: 18px;">Victory</strong>' %>
                      <br>- <strong class="text-success">Victory</strong> -
                    <% elsif combat_result.result == '<strong style="font-size: 18px;">Defeat</strong>' %>
                      <br>- <strong class="text-danger">Defeat</strong> -
                    <% end %>
                  </p>
                  <%= button_to "View", combat_result_character_path(current_user.selected_character, combat_result.id), class:"btn btn-outline-primary"%>
                </div>
              </div>
              <% unless @combat_results.last == combat_result %>
                <hr class="mx-auto" style="width: 80%;">
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<script>
    var audio = document.getElementById("arenaMusic");
    audio.volume = 0.02;
</script>

app/views/characters/equip_prompt.js.erb
<%= javascript_tag do %>
  const choice = prompt("Choose where to equip the item:\n1. Main Hand\n2. Off Hand");

  if (choice === "1") {
    // Call AJAX to equip in the main hand
    $.ajax({
      type: "POST",
      url: "<%= equip_item_character_path(@character, item_id: @new_item.id, slot: 'main_hand') %>",
      success: function() {
        location.reload(); // Refresh the page after successful equip
      }
    });
  } else if (choice === "2") {
    // Call AJAX to equip in the off hand
    $.ajax({
      type: "POST",
      url: "<%= equip_item_character_path(@character, item_id: @new_item.id, slot: 'off_hand') %>",
      success: function() {
        location.reload(); // Refresh the page after successful equip
      }
    });
  } else {
    // Handle invalid choice or cancel
    console.log("Invalid choice or canceled.");
  }
<% end %>

app/views/characters/leaderboard.html.erb
<div class="container text-center mt-5"> 
  <% @characters.each_with_index do |character, index| %>
    <div class="row mb-4">
      <div class="col-12">
        <h4 class="text-center"><%= "#{index + 1}." %></h4>
        <div class="card text-left mx-auto" style="border: 2px solid #000; padding: 15px; margin-bottom: 20px; width: 500px; height: 350px;">
          <div class="card-body text-center">
            <h5 class="card-header text-white bg-primary"><%= "#{character.character_name}, Character_title" %></h5>
            <br>
            <%= image_tag(character.race_image, style: 'width:80px; height:80px; border-radius:30%; margin-bottom:30px; box-shadow: 5px 5px 10px #888888;', class: 'card-img-top', alt: character.race_image) %>
            <h5 class="card-title"><small><%= character.race.capitalize %> <%= character.character_class.capitalize %> Level <%= character.level %></small></h5>

            <% current_experience = character.experience %>
            <% required_experience = character.required_experience_for_next_level %>
            <% progress_percentage = (current_experience.to_f / required_experience) * 100 %>
            <small><i>Experience: <%= "#{current_experience} / #{required_experience}" %></i></small>
            <div class="progress" style="max-height: 10px;">
              <div class="progress-bar bg-success" role="progressbar" style="width: <%= progress_percentage %>%;"></div>
            </div>
            <br>
            <%= link_to 'Profile', character_path(character), class: "btn btn-outline-primary" %>
          </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/characters/thaumaturge.html.erb
  <div class="mt-5" style="display: flex; flex-direction: row;">
    <div class="card text-left " style="border: 2px solid #000; box-shadow: 5px 5px 10px #888888; padding: 20px; height: 600px; width: 500px; margin-right: 20px; align-items: center;">
      <div class="card-body">
        <div style="position: relative; max-width: 100%;">
          <%= image_tag('npcs/thaumaturge.jpg', style: 'max-width:100%; height:auto; border: 5px solid #000; box-shadow: 2px 2px 10px #888888;', class: 'card-img-top', alt: "character_image") %>
          <h5 style="position: absolute; bottom: 0; left: 50%; transform: translateX(-50%); color: white; font-size: 24px; font-weight: bold; text-shadow: -2px -2px 2px #000, 2px -2px 2px #000, -2px 2px 2px #000, 2px 2px 2px #000; width: 90%; text-align: center;">Mekail</h5>
        </div>
        <br>
        <p class="card-text">Greetings, <%= @character.character_class.capitalize%>.</p>
        <p id="thaumaturge-dialogue">How can I assist you?</p>
      </div>
        <div class="card text-left mt-4" style="width: 500px; height: 200px; border: 2px solid #000; box-shadow: 5px 5px 10px #888888;">
            <div class="card-body">
                <h4 class="card-header text-center text-white bg-primary" style="width: 200px; margin: 0 auto; margin-bottom: 20px;">Restore Health</h4>
                <p class="text-center" style="margin-top: -20px;"><small>Heal back to full Health</small></p>
                <div class="text-center">
                    <%= form_tag(heal_character_path(@character), method: :post) do %>
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <%= submit_tag "Heal", class: "btn btn-outline-primary", style: "margin-top: 10px;" %>
                    <% end %>                  
                </div>
            </div>
        </div>
    </div>
    
    <div style="flex-row">
      <div class="mb-4">
        <div class="mx-auto">
          <% if current_user.present? && @character.user_id == current_user.id && current_user.selected_character.present? && current_user.selected_character.id == @character.id %>
            <!-- Inventory card -->
            <%= render partial: 'characters/inventory', locals: { character: @character } %>
          <% end %>
        </div>
      </div>

      <div class="card text-left mb-1" style="width: 800px; height: auto; border: 2px solid #000; box-shadow: 5px 5px 10px #888888;">
        <div class="card-body">
          <h4 class="card-header text-center text-white bg-primary" style="width: 200px; margin: 0 auto; margin-bottom: 20px;">Potions</h4>
          <div class="merchant-grid" style="display: grid; grid-template-columns: repeat(5, 1fr);">
            <% @healing_potions.each do |potion| %>
              <div class="merchant-item text-center item-tooltip" onmousemove="updateTooltipPosition(event, <%= potion.id %>)" onmouseover="showTooltip(<%= potion.id %>, 'Healing Potion')" onmouseout="hideTooltip(<%= potion.id %>)">
                <%= display_item_tooltip(potion, @character) %>
                <%= image_tag(potion.item_image, style: 'width: 100px; height: 100px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888;') %>
                <%= button_to "Purchase", add_to_inventory_character_path(@character, item_id: potion.id), method: :post, class: "btn btn-outline-primary btn-sm mt-1 mb-1", style:"width: 100px;", id: "purchaseButton#{potion.id}" %>
                <script>
                  // JavaScript code to show gold price on hover
                  document.getElementById('purchaseButton<%= potion.id %>').addEventListener('mouseover', function() {
                    this.innerText = '- <%= number_with_delimiter(potion.gold_price) %>';
                  });

                  document.getElementById('purchaseButton<%= potion.id %>').addEventListener('mouseout', function() {
                    this.innerText = 'Purchase';
                  });
                </script>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="card text-left mb-1" style="width: 800px; height: auto; border: 2px solid #000; box-shadow: 5px 5px 10px #888888;">
        <div class="card-body">
          <h4 class="card-header text-center text-white bg-primary" style="width: 200px; margin: 0 auto; margin-bottom: 20px;">Elixirs</h4>
          <div class="merchant-grid" style="display: grid; grid-template-columns: repeat(5, 1fr);">
            <% @elixirs.each do |elixir| %>
              <div class="merchant-item text-center item-tooltip" onmousemove="updateTooltipPosition(event, <%= elixir.id %>)" onmouseover="showTooltip(<%= elixir.id %>, 'Elixir')" onmouseout="hideTooltip(<%= elixir.id %>)">
                <%= display_item_tooltip(elixir, @character) %>
                <%= image_tag(elixir.item_image, style: 'width: 100px; height: 100px; border: 2px solid #000; box-shadow: 2px 2px 10px #888888;') %>
                <%= button_to "Purchase", add_to_inventory_character_path(@character, item_id: elixir.id), method: :post, class: "btn btn-outline-primary btn-sm mt-1 mb-1", style:"width: 100px;", id: "purchaseButton#{elixir.id}" %>
                <script>
                  // JavaScript code to show gold price on hover
                  document.getElementById('purchaseButton<%= elixir.id %>').addEventListener('mouseover', function() {
                    this.innerText = '- <%= number_with_delimiter(elixir.gold_price) %>';
                  });

                  document.getElementById('purchaseButton<%= elixir.id %>').addEventListener('mouseout', function() {
                    this.innerText = 'Purchase';
                  });
                </script>
              </div>
            <% end %>
          </div>
        </div>
      </div>

<script>
  function showTooltip(itemId, itemType) {
    const tooltip = document.getElementById(`tooltip_${itemId}`);
    if (tooltip) tooltip.style.display = 'block';
  }

  function hideTooltip(itemId) {
    const tooltip = document.getElementById(`tooltip_${itemId}`);
    if (tooltip) tooltip.style.display = 'none';
  }

  function updateTooltipPosition(event, itemId) {
    const tooltip = document.getElementById(`tooltip_${itemId}`);
    const offset = 10;
    const x = event.clientX + offset;
    const y = event.clientY + offset;

    // Check if the cursor is in the bottom half of the page
    const isBottomHalf = event.clientY > window.innerHeight / 2;

    // Adjust the tooltip position based on the cursor's location
    if (isBottomHalf) {
      tooltip.style.left = `${x}px`;
      tooltip.style.bottom = `${window.innerHeight - y}px`;
      tooltip.style.top = ''; // Reset top property
    } else {
      tooltip.style.left = `${x}px`;
      tooltip.style.top = `${y}px`;
      tooltip.style.bottom = ''; // Reset bottom property
    }
  }
</script>